"""Timezone-safe scheduling helpers shared by the API and tests.

Slots are persisted because stable, event-scoped identifiers make availability
validation and aggregation straightforward. They are generated by walking UTC
between local midnights, then filtering by the configured local working hours.
That preserves daylight-saving gaps and repeated local times correctly.
"""

from collections import defaultdict
from datetime import datetime, timedelta, timezone
from urllib.parse import urlencode
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError
from .models import ScheduleSelection


def get_timezone(name):
    try:
        return ZoneInfo(name)
    except (ZoneInfoNotFoundError, TypeError):
        return None


def generate_slot_datetimes(local_date, start_local_time, end_local_time, timezone_name, interval_minutes):
    zone = get_timezone(timezone_name)
    if not zone or end_local_time <= start_local_time or interval_minutes not in (15, 30, 45, 60):
        return []

    start_of_day = datetime.combine(local_date, datetime.min.time(), tzinfo=zone).astimezone(timezone.utc)
    next_day = datetime.combine(local_date + timedelta(days=1), datetime.min.time(), tzinfo=zone).astimezone(timezone.utc)
    interval = timedelta(minutes=interval_minutes)
    current = start_of_day
    slots = []
    while current < next_day:
        local = current.astimezone(zone)
        if local.date() == local_date and start_local_time <= local.time().replace(tzinfo=None) < end_local_time:
            slots.append((current, current + interval))
        current += interval
    return slots


def required_slots(slots, start_slot, duration_minutes, interval_minutes):
    needed = duration_minutes // interval_minutes
    if needed < 1 or duration_minutes % interval_minutes:
        return []
    ordered = sorted(slots, key=lambda slot: slot.start_at)
    positions = {slot.id: index for index, slot in enumerate(ordered)}
    start_index = positions.get(start_slot.id)
    if start_index is None:
        return []
    window = ordered[start_index : start_index + needed]
    if len(window) != needed:
        return []
    expected = start_slot.start_at
    interval = timedelta(minutes=interval_minutes)
    for slot in window:
        if slot.start_at != expected:
            return []
        expected += interval
    return window


def availability_summary(event, include_owner=True):
    """Return counts plus ranked, duration-aware candidate meeting windows."""
    slots = list(event.slots.order_by("start_at"))
    participants = list(event.participants.filter(is_owner=False) if not include_owner else event.participants.all())
    participant_ids = [participant.id for participant in participants]
    selected_by_participant = defaultdict(set)
    for participant_id, slot_id in ScheduleSelection.objects.filter(participant_id__in=participant_ids).values_list("participant_id", "slot_id"):
        selected_by_participant[participant_id].add(slot_id)

    total = len(participants)
    counts = {}
    for slot in slots:
        available = sum(slot.id in selected_by_participant[participant_id] for participant_id in participant_ids)
        counts[str(slot.public_id)] = {"available": available, "total": total, "percentage": round((available / total) * 100) if total else 0}

    windows = []
    for start_slot in slots:
        window = required_slots(slots, start_slot, event.meeting_duration_minutes, event.interval_minutes)
        if not window:
            continue
        slot_ids = {slot.id for slot in window}
        available = sum(slot_ids.issubset(selected_by_participant[participant_id]) for participant_id in participant_ids)
        windows.append({
            "slot": start_slot,
            "slot_ids": [str(slot.public_id) for slot in window],
            "end_at": window[-1].end_at,
            "available": available,
            "total": total,
            "percentage": round((available / total) * 100) if total else 0,
        })
    windows.sort(key=lambda item: (-item["available"], -item["percentage"], item["slot"].start_at))
    return counts, windows


def ics_text(event, meeting):
    def clean(value):
        return str(value or "").replace("\\", "\\\\").replace(";", "\\;").replace(",", "\\,").replace("\n", "\\n")

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    start = meeting.start_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    end = meeting.end_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Portfolio//Scheduling Poll//EN", "CALSCALE:GREGORIAN",
        "BEGIN:VEVENT", f"UID:{event.public_id}@portfolio.local", f"DTSTAMP:{stamp}", f"DTSTART:{start}", f"DTEND:{end}",
        f"SUMMARY:{clean(event.title)}", f"DESCRIPTION:{clean(event.description)}", f"LOCATION:{clean(event.location)}", "END:VEVENT", "END:VCALENDAR", "",
    ]
    return "\r\n".join(lines)


def google_calendar_url(event, meeting):
    start = meeting.start_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    end = meeting.end_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    query = urlencode({"action": "TEMPLATE", "text": event.title, "dates": f"{start}/{end}", "details": event.description, "location": event.location, "ctz": event.timezone})
    return f"https://calendar.google.com/calendar/render?{query}"
