# Generated by Django 5.0.1 on 2026-08-18 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_private_chat_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_date', models.DateField()),
                ('start_local_time', models.TimeField()),
                ('end_local_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_owner', models.BooleanField(default=False)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('local_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='allow_participant_editing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='availability_visibility',
            field=models.CharField(choices=[('HIDDEN', 'Hide participant details'), ('AGGREGATE', 'Show aggregate counts only'), ('NAMES', 'Show participant names')], default='AGGREGATE', max_length=12),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='meeting_duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], default='OPEN', max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['public_id'], name='portfolio_s_public__15acf5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['status', 'response_deadline'], name='portfolio_s_status_d748c5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['owner', 'updated_at'], name='portfolio_s_owner_i_27bb68_idx'),
        ),
        migrations.AddField(
            model_name='confirmedmeeting',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_meeting', to='portfolio.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduledate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='portfolio.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduleparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='portfolio.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduleparticipantsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to='portfolio.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduleparticipantsession',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='portfolio.scheduleparticipant'),
        ),
        migrations.AddField(
            model_name='scheduleselection',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='portfolio.scheduleparticipant'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='portfolio.scheduleevent'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='schedule_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='portfolio.scheduledate'),
        ),
        migrations.AddField(
            model_name='scheduleselection',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='portfolio.scheduleslot'),
        ),
        migrations.AddIndex(
            model_name='confirmedmeeting',
            index=models.Index(fields=['start_at'], name='portfolio_c_start_a_e4a9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledate',
            index=models.Index(fields=['event', 'local_date'], name='portfolio_s_event_i_9166ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledate',
            constraint=models.UniqueConstraint(fields=('event', 'local_date'), name='unique_schedule_date_per_event'),
        ),
        migrations.AddIndex(
            model_name='scheduleparticipant',
            index=models.Index(fields=['event', 'is_owner'], name='portfolio_s_event_i_fd1263_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleparticipantsession',
            index=models.Index(fields=['event', 'expires_at'], name='portfolio_s_event_i_356e01_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleparticipantsession',
            index=models.Index(fields=['participant', 'expires_at'], name='portfolio_s_partici_d3aaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['event', 'start_at'], name='portfolio_s_event_i_0ed951_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['public_id'], name='portfolio_s_public__731680_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('event', 'start_at'), name='unique_schedule_slot_start'),
        ),
        migrations.AddIndex(
            model_name='scheduleselection',
            index=models.Index(fields=['slot'], name='portfolio_s_slot_id_e3cc62_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleselection',
            index=models.Index(fields=['participant'], name='portfolio_s_partici_8b1d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleselection',
            constraint=models.UniqueConstraint(fields=('participant', 'slot'), name='unique_schedule_selection'),
        ),
    ]
