# Generated by Django 5.0.1 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_scheduling_poll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionWheel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(default=portfolio.models.public_id, editable=False, max_length=48, unique=True)),
                ("subject", models.CharField(max_length=180)),
                ("is_active", models.BooleanField(default=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_wheels", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="DecisionParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=60)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("wheel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="portfolio.decisionwheel")),
            ],
        ),
        migrations.CreateModel(
            name="DecisionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=120)),
                ("participant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="options", to="portfolio.decisionparticipant")),
                ("wheel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="portfolio.decisionwheel")),
            ],
        ),
        migrations.CreateModel(
            name="DecisionParticipantSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="portfolio.decisionparticipant")),
                ("wheel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participant_sessions", to="portfolio.decisionwheel")),
            ],
        ),
        migrations.CreateModel(
            name="DecisionSpin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="spins", to="portfolio.decisionoption")),
                ("participant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spins", to="portfolio.decisionparticipant")),
                ("wheel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="spins", to="portfolio.decisionwheel")),
            ],
        ),
        migrations.AddField(
            model_name="decisionwheel",
            name="decided_option",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_in", to="portfolio.decisionoption"),
        ),
        migrations.AddIndex(model_name="decisionwheel", index=models.Index(fields=["public_id"], name="portfolio_d_public__f6ca14_idx")),
        migrations.AddIndex(model_name="decisionwheel", index=models.Index(fields=["owner", "updated_at"], name="portfolio_d_owner_i_909556_idx")),
        migrations.AddIndex(model_name="decisionwheel", index=models.Index(fields=["is_active"], name="portfolio_d_is_acti_724cb6_idx")),
        migrations.AddIndex(model_name="decisionparticipant", index=models.Index(fields=["wheel", "created_at"], name="portfolio_d_wheel_i_116786_idx")),
        migrations.AddIndex(model_name="decisionparticipantsession", index=models.Index(fields=["wheel", "expires_at"], name="portfolio_d_wheel_i_6e4220_idx")),
        migrations.AddIndex(model_name="decisionparticipantsession", index=models.Index(fields=["participant", "expires_at"], name="portfolio_d_partici_3984d4_idx")),
        migrations.AddIndex(model_name="decisionoption", index=models.Index(fields=["wheel", "created_at"], name="portfolio_d_wheel_i_1ff037_idx")),
        migrations.AddIndex(model_name="decisionspin", index=models.Index(fields=["wheel", "created_at"], name="portfolio_d_wheel_i_7e02a5_idx")),
    ]
