<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from "vue";
import { api, apiForm } from "../api";
import ChatComposer from "../components/ChatComposer.vue";
import ChatMessage from "../components/ChatMessage.vue";
const props=defineProps<{ token:string }>();
type Message={id:string;sender:string;senderRole:"OWNER"|"GUEST";body:string;createdAt:string;attachments:{id:string;url:string;mimeType:string;width:number;height:number}[]};
const name=ref(""),pin=ref(""),joined=ref(false),messages=ref<Message[]>([]),error=ref(""),busy=ref(false),poller=ref<number|undefined>(),list=ref<HTMLElement|null>(null),newMessages=ref(false);
const atBottom=computed(()=>!list.value||list.value.scrollHeight-list.value.scrollTop-list.value.clientHeight<120);
function merge(incoming:Message[]){const known=new Set(messages.value.map(m=>m.id));const fresh=incoming.filter(m=>!known.has(m.id));if(fresh.length){messages.value=[...messages.value,...fresh];if(atBottom.value)nextTick(()=>list.value?.scrollTo({top:list.value.scrollHeight,behavior:"smooth"}));else newMessages.value=true}}
async function load(scroll=true){try{const result=await api<{messages:Message[]}>(`/chat/${props.token}/messages/`);if(!joined.value){joined.value=true;messages.value=result.messages}else merge(result.messages);if(scroll)nextTick(()=>list.value?.scrollTo({top:list.value.scrollHeight}))}catch{joined.value=false}}
async function join(){busy.value=true;error.value="";try{const result=await api<{messages:Message[]}>(`/chat/${props.token}/join/`,"POST",{name:name.value,pin:pin.value});messages.value=result.messages;joined.value=true;nextTick(()=>list.value?.scrollTo({top:list.value.scrollHeight}))}catch(e){error.value=e instanceof Error?e.message:"Unable to join this conversation."}finally{busy.value=false}}
async function send(body:string,image:File|null){busy.value=true;error.value="";try{let result:{message:Message};if(image){const form=new FormData();form.append("image",image);form.append("body",body);result=await apiForm(`/chat/${props.token}/attachments/`,form)}else result=await api(`/chat/${props.token}/send/`,"POST",{body});messages.value.push(result.message);nextTick(()=>list.value?.scrollTo({top:list.value?.scrollHeight||0,behavior:"smooth"}))}catch(e){error.value=e instanceof Error?e.message:"Unable to send. Please retry."}finally{busy.value=false}}
function scrollNew(){newMessages.value=false;list.value?.scrollTo({top:list.value.scrollHeight,behavior:"smooth"})}
onMounted(async()=>{await load();poller.value=window.setInterval(()=>{if(joined.value)load(false)},4000)});onBeforeUnmount(()=>{if(poller.value)window.clearInterval(poller.value)});
</script>
<template><main id="main" class="chat-page"><section class="chat-shell"><header class="chat-header"><div><div class="eyebrow">Private conversation</div><h1>{{ joined ? 'Conversation' : 'You’ve been invited.' }}</h1></div><p>{{ joined ? 'Messages are private to this room.' : 'Enter the name and four-digit PIN you received. No account is needed.' }}</p></header><form v-if="!joined" class="chat-entry form" @submit.prevent="join"><label class="field">Your name<input v-model="name" required maxlength="60" autocomplete="name"/></label><label class="field pin-field">Four-digit PIN<input v-model="pin" required maxlength="4" inputmode="numeric" pattern="[0-9]{4}" autocomplete="one-time-code" aria-describedby="pin-help"/><small id="pin-help">The room owner shares this separately from the link.</small></label><p v-if="error" class="error" role="alert">{{ error }}</p><button class="button" :disabled="busy">{{ busy?'Joining…':'Enter chat' }}</button></form><template v-else><div ref="list" class="message-list" aria-live="polite" @scroll="newMessages=false"><p v-if="!messages.length" class="chat-empty">No messages yet. Start the conversation.</p><ChatMessage v-for="message in messages" :key="message.id" :message="message" viewer-role="GUEST"/></div><button v-if="newMessages" class="new-message-button" @click="scrollNew">New messages ↓</button><p v-if="error" class="error" role="alert">{{ error }}</p><ChatComposer :key="busy?'busy':'ready'" @send="send"/></template></section></main></template>
