<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";
import { publishedProjects } from "../data";
const route = useRoute();
const project = computed(() => publishedProjects.find((item) => item.slug === route.params.slug));
</script>

<template><main id="main" class="page"><template v-if="project"><header class="shell case-hero"><div class="eyebrow">{{ project.status || 'Project case study' }}</div><h1>{{ project.name }}</h1><p class="lead">{{ project.summary }}</p><div class="actions"><a v-if="project.liveUrl" class="button external" :href="project.liveUrl" target="_blank" rel="noopener noreferrer">Visit website</a><a v-if="project.github" class="button secondary external" :href="project.github" target="_blank" rel="noopener noreferrer">GitHub</a></div></header><section class="section"><div class="shell case-layout"><article class="body-copy"><div class="project-visual" :aria-label="`${project.name} project visual`"><span>{{ project.name }}</span></div><h2>Overview</h2><p>{{ project.summary }}</p><h2>Problem</h2><p>{{ project.problem }}</p><h2>Solution</h2><p>{{ project.solution }}</p><template v-if="project.features?.length"><h2>Key features</h2><ul><li v-for="feature in project.features" :key="feature">{{ feature }}</li></ul></template><template v-if="project.challenges?.length"><h2>Engineering challenges</h2><div v-for="challenge in project.challenges" :key="challenge.title"><h3>{{ challenge.title }}</h3><p>{{ challenge.detail }}</p></div></template><template v-if="project.learnings?.length"><h2>What I learned</h2><ul><li v-for="learning in project.learnings" :key="learning">{{ learning }}</li></ul></template></article><aside class="case-aside"><div><span>Role</span><b>{{ project.role || 'Independent builder' }}</b></div><div><span>Technologies</span><div class="tags"><span v-for="tech in project.technologies" :key="tech" class="tag">{{ tech }}</span></div></div></aside></div></section></template><section v-else class="shell page-head"><div class="eyebrow">404</div><h1>Project not found.</h1><p class="lead">This project may be unpublished or the link is incomplete.</p><RouterLink class="button" to="/projects">View projects</RouterLink></section></main></template>
