<script setup lang="ts">
import { computed, ref } from "vue";
import { api } from "../api";
import { profile, publishedAchievements, publishedEducation, publishedExperience, publishedProjects, skills } from "../data";
const props = defineProps<{ page: string }>();
const titles: Record<string, { label: string; heading: string; intro: string }> = { about:{label:"About",heading:"A thoughtful approach to building software.",intro:"The context behind my work, the systems I enjoy shaping, and the way I collaborate."},experience:{label:"Experience",heading:"Work that holds up.",intro:"Roles, responsibilities, and technical contributions."},education:{label:"Education",heading:"A foundation for continued learning.",intro:"Academic work, relevant study, and accomplishments."},projects:{label:"Projects",heading:"Products, experiments, and engineering work.",intro:"Each project explains the problem, the technical decisions, and the outcome."},resume:{label:"Resume",heading:"The concise version.",intro:"A complete record of my experience and education."},contact:{label:"Contact",heading:"Let’s connect.",intro:"For software engineering opportunities, project discussions, and collaborations."} };
const content = computed(() => titles[props.page]); const sent = ref(""); const error = ref(""); const form = ref({ name:"", email:"", subject:"", message:"", website:"" });
async function send() { sent.value=""; error.value=""; try { const result = await api<{success:string}>("/contact/", "POST", form.value); sent.value=result.success; form.value={name:"",email:"",subject:"",message:"",website:""}; } catch (e) { error.value=e instanceof Error ? e.message : "Your message could not be sent."; } }
</script>

<template><main id="main" class="page"><header class="shell page-head"><div class="eyebrow">{{ content.label }}</div><h1>{{ content.heading }}</h1><p class="lead">{{ content.intro }}</p></header>
  <section v-if="page==='about'" class="section"><div class="shell two-col"><div class="body-copy"><h2>What I build</h2><p v-if="profile.about">{{ profile.about }}</p><p v-else>I’m interested in end-to-end software work: turning ambiguous problems into well-considered products, then supporting them with maintainable systems.</p><h2>How I work</h2><p>I value clear problem framing, practical decisions, and communication that makes the next step obvious.</p></div><aside><div v-if="profile.currently" class="education-item"><div class="eyebrow">Currently</div><p>{{ profile.currently }}</p></div><div class="education-item"><div class="eyebrow">Toolkit</div><div class="tags"><template v-for="group in skills" :key="group.category"><span v-for="item in group.items" :key="item" class="tag">{{ item }}</span></template></div></div></aside></div></section>
  <section v-else-if="page==='experience'" class="section"><div class="shell"><div v-if="publishedExperience.length" class="timeline"><article v-for="item in publishedExperience" :key="`${item.company}-${item.role}`" class="timeline-item"><div class="eyebrow">{{ item.dates }}</div><h3>{{ item.role }}</h3><strong>{{ item.company }}<span v-if="item.location"> · {{ item.location }}</span></strong><ul><li v-for="point in item.highlights" :key="point">{{ point }}</li></ul><div class="tags"><span v-for="tech in item.technologies" :key="tech" class="tag">{{ tech }}</span></div></article></div><div v-else class="empty-state">Verified experience entries will appear here once they are added to the portfolio content file.</div></div></section>
  <section v-else-if="page==='education'" class="section"><div class="shell"><div v-if="publishedEducation.length" class="education-list"><article v-for="item in publishedEducation" :key="item.school" class="education-item"><div class="eyebrow">{{ item.dates }}</div><h3>{{ item.school }}</h3><strong>{{ item.degree }}<span v-if="item.location"> · {{ item.location }}</span></strong><ul v-if="item.details"><li v-for="detail in item.details" :key="detail">{{ detail }}</li></ul></article></div><div v-else class="empty-state">Education is intentionally hidden until verified information is added.</div><div v-if="publishedAchievements.length" class="education-list" style="margin-top:64px"><div class="eyebrow">Achievements</div><article v-for="item in publishedAchievements" :key="item.title" class="education-item"><h3>{{ item.title }}</h3><p>{{ item.organization }} · {{ item.year }}</p><p v-if="item.detail">{{ item.detail }}</p></article></div></div></section>
  <section v-else-if="page==='projects'" class="section"><div class="shell"><div v-if="publishedProjects.length" class="project-grid"><RouterLink v-for="project in publishedProjects" :key="project.slug" class="project-card" :to="`/projects/${project.slug}`"><div class="eyebrow">{{ project.status || 'Case study' }}</div><h2>{{ project.name }}</h2><p>{{ project.summary }}</p><div class="tags"><span v-for="tech in project.technologies" :key="tech" class="tag">{{ tech }}</span></div></RouterLink></div><div v-else class="empty-state">Projects are published only after their case studies and links are ready.</div></div></section>
  <section v-else-if="page==='resume'" class="section"><div class="shell"><div class="actions"><a v-if="profile.resumeUrl" :href="profile.resumeUrl" class="button" download>Download PDF</a><a v-if="profile.resumeUrl" :href="profile.resumeUrl" class="button secondary" target="_blank" rel="noopener noreferrer">Open resume</a><RouterLink class="button secondary" to="/contact">Contact me</RouterLink></div><iframe v-if="profile.resumeUrl" class="resume-frame" :src="profile.resumeUrl" title="Resume PDF" style="margin-top:32px"></iframe><div v-else class="empty-state" style="margin-top:32px">A verified resume PDF can be added by setting <code>resumeUrl</code> in <code>src/data.ts</code>.</div></div></section>
  <section v-else class="section"><div class="shell two-col"><div class="body-copy"><h2>Elsewhere</h2><p v-if="profile.email"><a class="text-link" :href="`mailto:${profile.email}`">{{ profile.email }}</a></p><p v-if="profile.github"><a class="text-link external" :href="profile.github" target="_blank" rel="noopener noreferrer">GitHub</a></p><p v-if="profile.linkedin"><a class="text-link external" :href="profile.linkedin" target="_blank" rel="noopener noreferrer">LinkedIn</a></p><p v-if="!profile.email && !profile.github && !profile.linkedin" class="empty-state">Public contact links will appear here once verified details are added.</p></div><form class="form" @submit.prevent="send"><label class="field">Name<input v-model="form.name" required autocomplete="name"/></label><label class="field">Email<input v-model="form.email" type="email" required autocomplete="email"/></label><label class="field">Subject<input v-model="form.subject" required/></label><label class="field">Message<textarea v-model="form.message" required/></label><input v-model="form.website" aria-hidden="true" tabindex="-1" autocomplete="off" style="display:none"/><p v-if="error" class="error">{{ error }}</p><p v-if="sent" class="notice">{{ sent }}</p><button class="button" type="submit">Send message</button></form></div></section>
</main></template>
